language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - setup=basic
    - coverage=true
    - illuminate=default

sudo: false

branches:
  except:
    - gh-pages
    - /analysis-.*/

before_install:
  - if [[ $coverage = 'false' ]]; then phpenv config-rm xdebug.ini || true; fi
  - composer global require hirak/prestissimo --update-no-dev

install:
  - if [[ $setup = 'basic'  ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-lowest; fi
  - if [[ $illuminate != 'default' ]]; then travis_retry composer require --dev --update-with-dependencies --prefer-dist --no-interaction --no-suggest illuminate/support "$illuminate"; fi

script:
  - if [[ $coverage = 'true' ]]; then composer test-cover; else composer test; fi

after_success:
  - if [[ $coverage = 'true' ]]; then bash <(curl -s https://codecov.io/bash); fi

matrix:
  include:
    - php: 7.1.3
      env: setup=lowest

    - php: 7.2
      env: setup=lowest
    - php: 7.2
      env: illuminate=6.*

    - php: 7.3
      env: setup=lowest
    - php: 7.3
      env: illuminate=5.8

    - php: 7.4
      env: setup=lowest
    - php: 7.4
      env: illuminate=5.8
    - php: 7.4
      env: illuminate=6.*
